/**
 * @file tfo.cpp
 * @brief TFO cookie implementation (RFC 7413).
 */

#include <xtcp/core/tfo.h>

#include <chrono>
#include <random>

#if defined(_WIN32)
#include <windows.h>
#include <bcrypt.h>
#if defined(_MSC_VER)
#pragma comment(lib, "bcrypt.lib")
#endif
#endif

namespace xtcp {
    namespace core {
        namespace {
            inline UInt64 TfoRotl64(UInt64 x, UInt32 n) noexcept {
                return (x << n) | (x >> (64 - n));
            }
        }

        TfoCookie::TfoCookie() noexcept {
            // The cookie secret is process-global: a cookie generated by one
            // connection must verify on another (RFC 7413 clients present
            // the cookie on a NEW connection). Per-instance secrets would
            // invalidate every cookie across reconnections.
            static const UInt64 shared_secret = []() {
                UInt64 s = 0;
#if defined(_WIN32)
                // Windows: OS CSPRNG (BCryptGenRandom, system preferred RNG).
                const NTSTATUS st = BCryptGenRandom(
                    NULLPTR, reinterpret_cast<PUCHAR>(&s),
                    static_cast<ULONG>(sizeof(s)),
                    BCRYPT_USE_SYSTEM_PREFERRED_RNG);
                if (0 == st) {
                    return s;
                }
#endif
                // Non-Windows fallback (and Windows failure path): the platform
                // entropy source, not a clock-derived value (the old steady_clock
                // secret was recoverable from an estimated uptime + one captured
                // cookie because every mix step was a bijection).
                std::random_device rd;
                s = (static_cast<UInt64>(rd()) << 32) ^ rd();
                return (0 == s) ? 1 : s;
            }();
            secret_ = shared_secret;
        }

        UInt64 TfoCookie::Hash(const UInt32 addr[4], UInt64 time_disc) const noexcept {
            UInt64 h = secret_ ^ time_disc;
            h = TfoRotl64(h, 27) * 0xBF58476D1CE4E5B9ull;
            for (UInt32 i = 0; i < 4; ++i) {
                h ^= addr[i];
                h = TfoRotl64(h, 17) * 0x94D049BB133111EBull;
            }
            h ^= h >> 31;
            return h;
        }

        void TfoCookie::Generate(const UInt32 addr[4], Byte out[kTfoCookieLen]) const noexcept {
            const UInt64 tag = static_cast<UInt64>(
                std::chrono::duration_cast<std::chrono::seconds>(
                    std::chrono::steady_clock::now().time_since_epoch()).count()) >> 8;
            const UInt64 h = Hash(addr, tag);
            for (UInt32 i = 0; i < kTfoCookieLen; ++i) {
                out[i] = static_cast<Byte>((h >> (i * 8)) & 0xFF);
            }
        }

        bool TfoCookie::Check(const UInt32 addr[4], const Byte cookie[kTfoCookieLen]) const noexcept {
            // Accept within a rolling replay window: 56 buckets x 256 s each
            // (14336 s ~ 4 h). A cookie learned on a fresh connection always
            // matches bucket 0 (generated in the current bucket); the older
            // buckets only tolerate clients that cached the cookie for a few
            // hours. RFC 7413 allows a limited validity window; a server may
            // regenerate on expiry. (The previous 129-bucket window ~ 9.2 h
            // needlessly widened replay.)
            const UInt64 now = static_cast<UInt64>(
                std::chrono::duration_cast<std::chrono::seconds>(
                    std::chrono::steady_clock::now().time_since_epoch()).count()) >> 8;
            for (Int64 window = 0; window <= 55; ++window) {
                const UInt64 tag = now - static_cast<UInt64>(window);
                const UInt64 h = Hash(addr, tag);
                // Constant-time comparison: no early exit on mismatch, so the
                // comparison latency does not leak cookie bytes (timing side
                // channel).
                Byte diff = 0;
                for (UInt32 i = 0; i < kTfoCookieLen; ++i) {
                    diff |= static_cast<Byte>(
                        cookie[i] ^ static_cast<Byte>((h >> (i * 8)) & 0xFF));
                }
                if (0 == diff) {
                    return true;
                }
            }
            return false;
        }
    }
}
