set(LWIP_SOURCES
        third_party/lwip/api/api_lib.c
        third_party/lwip/api/api_msg.c
        third_party/lwip/api/err.c
        third_party/lwip/api/if_api.c
        third_party/lwip/api/netbuf.c
        third_party/lwip/api/netdb.c
        third_party/lwip/api/netifapi.c
        third_party/lwip/api/sockets.c
        third_party/lwip/api/tcpip.c
        third_party/lwip/core/altcp_alloc.c
        third_party/lwip/core/altcp_tcp.c
        third_party/lwip/core/altcp.c
        third_party/lwip/core/def.c
        third_party/lwip/core/dns.c
        third_party/lwip/core/inet_chksum.c
        third_party/lwip/core/init.c
        third_party/lwip/core/ip.c
        third_party/lwip/core/mem.c
        third_party/lwip/core/memp.c
        third_party/lwip/core/netif.c
        third_party/lwip/core/pbuf.c
        third_party/lwip/core/raw.c
        third_party/lwip/core/stats.c
        third_party/lwip/core/sys.c
        third_party/lwip/core/tcp_in.c
        third_party/lwip/core/tcp_out.c
        third_party/lwip/core/tcp.c
        third_party/lwip/core/timeouts.c
        third_party/lwip/core/udp.c
        third_party/lwip/core/ipv4/acd.c
        third_party/lwip/core/ipv4/autoip.c
        third_party/lwip/core/ipv4/dhcp.c
        third_party/lwip/core/ipv4/etharp.c
        third_party/lwip/core/ipv4/icmp.c
        third_party/lwip/core/ipv4/igmp.c
        third_party/lwip/core/ipv4/ip4_addr.c
        third_party/lwip/core/ipv4/ip4_frag.c
        third_party/lwip/core/ipv4/ip4.c
        third_party/lwip/core/ipv6/dhcp6.c
        third_party/lwip/core/ipv6/ethip6.c
        third_party/lwip/core/ipv6/icmp6.c
        third_party/lwip/core/ipv6/inet6.c
        third_party/lwip/core/ipv6/ip6_addr.c
        third_party/lwip/core/ipv6/ip6_frag.c
        third_party/lwip/core/ipv6/ip6.c
        third_party/lwip/core/ipv6/mld6.c
        third_party/lwip/core/ipv6/nd6.c
        third_party/lwip/my/sys_arch.c
)